### ISSUE TITLE
[REFACTOR] 약 페이지 렌더링 오류 수정

### ISSUE THREAD

**Issue by vvzvvv** [feelSpring/spring#101]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 약 기록 생성시 페이지가 바로 랜더링 되지 않는 문제 리팩토링

## TODO

- [x] 약 기록을 가져오고 난 후, 렌더링이 되게 해야함
