### ISSUE TITLE
[FEATURE] 테스트 기능

### ISSUE THREAD

**Issue by choiyoorim** [feelSpring/spring#11]
## 🌴 작업 브랜치 
`feature/#11`

## 💼 TASK 개요 
테스트 기능 구현

## ✅ TODO 및 진행현황 

- [ ] 테스트 post 기능 구현
- [ ] post 시 데이터베이스에 저장 
- [ ] 테스트 get 기능 구현
- [ ] get 하면 뷰에 나타남
