### ISSUE TITLE
[REFACTOR] 수정시 사진 저장 안되는 문제 해결

### ISSUE THREAD

**Issue by choiyoorim** [feelSpring/spring#30]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- css 바꾸기
- 수정시 사진 변경 없으면 사진 없다는 에러 발생 => Update와 Post가 하나로 작동하기 때문

## TODO

- [ ] css 바꾸기
- [ ] 수정시 사진 변경 없이 저장 가능하게끔 default 사진 추가
