### ISSUE TITLE
[REFACTOR] 약 기록 CSS 수정

### ISSUE THREAD

**Issue by vvzvvv** [feelSpring/spring#43]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 약 기록 내의 css 수정

## TODO

- [x] 차트 css
- [x] 처방약, 복용기록 css
- [x] 수정, 삭제 팝업창 css
