### ISSUE TITLE
[REFACTOR] 전체적인 CSS 및 토큰 기능 수정

### ISSUE THREAD

**Issue by choiyoorim** [feelSpring/spring#45]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [X] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 이런 걸 해야해

## TODO

- [ ] CSS 수정(전반적으로 안 맞는 점, 이상한 점 등)
- [ ] 백엔드 기능 중 잘 안되는 부분들
