### ISSUE TITLE
[REFACTOR] 약 페이지 css 수정

### ISSUE THREAD

**Issue by vvzvvv** [feelSpring/spring#58]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

약 페이지 css를 메인 컬러에 맞게 전면 수정

## TODO

- [x] 복용약 페이지 css 변경
- [x] 팝업창 css 변경
