### ISSUE TITLE
[REFACTOR] 로그인 페이지 CSS 변경

### ISSUE THREAD

**Issue by senzoo-oh** [feelSpring/spring#60]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 기존 프로젝트에서 디자인 변경으로 인해 로그인 페이지 css 변경

## TODO

- [x] 스프링 로고 추가
- [x] 폰트 적용
- [x] 메뉴 제거
