### ISSUE TITLE
[FEATURE] 마이페이지 백엔드

### ISSUE THREAD

**Issue by choiyoorim** [feelSpring/spring#75]
## 🌴 작업 브랜치 
`feature/#75`

## 💼 TASK 개요 
마이페이지 백엔드 기능 제작

## ✅ TODO 및 진행현황 

- [ ] GET 동의요청 내용
- [ ] POST 동의 허락 / 거절 / 요청 끊기
- [ ] GET 동의 내용 
- [ ] PUT 동의 내용 수정
