### ISSUE TITLE
[FEATURE] 환자 추가창

### ISSUE THREAD

**Issue by vvzvvv** [feelSpring/spring#77]
## 🌴 작업 브랜치 
`feature/#77`
## 💼 TASK 개요 
환자 추가 팝업창 프론트 작성

## ✅ TODO 및 진행현황 

- [x] 환자 검색창
- [x] 환자 목록
- [x] 환자 추가 신청 버튼
- 
- [x] 환자 검색
- [x] 환자 리스트 불러오기
- [ ] 친구 추가 / 승인 대기 버튼
