### ISSUE TITLE
[REFACTOR] 의사 페이지 수정

### ISSUE THREAD

**Issue by vvzvvv** [feelSpring/spring#87]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

의사 메인 페이지에서 환자 추가창과 연결

## TODO

- [ ] 환자 추가창과 연결
- [ ] 의사 메인 페이지 css 수정
