### ISSUE TITLE
[REFACTOR] 의사 메인페이지 수정

### ISSUE THREAD

**Issue by seoyeon0918** [feelSpring/spring#90]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요
의사 메인페이지 오류 수정

## TODO

- [x] 검색안했을때 전체 환자 뜨게 할 get 컨트롤러 추가
- [x] 쿼리문 오타 수정
- [x]  요청 보낸 목록 불러오는 스크립트 추가
- [x] 라우터 추가
- [x] ejs 파일 수정
