### ISSUE TITLE
[REFACTOR] 환자 목록 오류 수정

### ISSUE THREAD

**Issue by vvzvvv** [feelSpring/spring#94]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 이런 걸 해야해

## TODO

- [ ] 토큰에서 의사 아이디 가져오기 
- [ ] 기능 수정
